[tool.poetry]
name = "whisper-bisom"
version = "0.1.0"
description = ""
authors = ["Romain Florentz <romain@florentz-consulting.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torchaudio = "^2.7.0"
soundfile = "^0.13.1"
torch = "^2.7.0"
librosa = "^0.11.0"
transformers = {extras = ["torch"], version = "^4.51.3"}
jiwer = "^3.1.0"
pandas = "^2.2.3"
matplotlib = "^3.10.1"
seaborn = "^0.13.2"
datasets = "^3.5.0"
fire = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
